// NOVA GRAPHIK — curated Lucide icon registry.
// The brand uses thin even-stroke (1.5–2px) line icons (Lucide).
// We register only the icons used across the site for tree-shaking,
// and expose a kebab-case `name` lookup matching the design source.
import type { Component } from 'vue'
import {
  Palette, Printer, Share2, Clapperboard, Box, Camera, Monitor, Mail,
  ArrowRight, ArrowUpRight, ArrowLeft, Check, Eye, EyeOff, LayoutDashboard,
  FileText, Image as ImageIcon, PenLine, Users, Tag, Settings, Plus,
  GripVertical, Phone, MapPin, Quote,
  Sparkles, Menu, X, LogOut, Lock, Save, Trash2, ChevronUp, ChevronDown,
  Sun, Moon, User,
  Briefcase, Star, Heart, Award, Zap, Layers, PenTool, Globe, Rocket,
  Lightbulb, Megaphone, Film, Video, Smartphone, ShoppingBag, TrendingUp,
  Compass, Target, Gem, Crown, Brush, ShieldCheck, Pencil, Wand2,
  Maximize, Square, RectangleHorizontal, RectangleVertical, File as FileIcon,
  Download, RefreshCw, Inbox, Calendar, Copy,
} from '@lucide/vue'
import { Instagram, Facebook, Youtube, Tiktok } from './socialIcons'

export const ICONS: Record<string, Component> = {
  'palette': Palette,
  'printer': Printer,
  'share-2': Share2,
  'clapperboard': Clapperboard,
  'box': Box,
  'camera': Camera,
  'monitor': Monitor,
  'mail': Mail,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'arrow-left': ArrowLeft,
  'check': Check,
  'eye': Eye,
  'eye-off': EyeOff,
  'layout-dashboard': LayoutDashboard,
  'file-text': FileText,
  'image': ImageIcon,
  'pen-line': PenLine,
  'users': Users,
  'tag': Tag,
  'settings': Settings,
  'plus': Plus,
  'grip-vertical': GripVertical,
  'phone': Phone,
  'map-pin': MapPin,
  'instagram': Instagram,
  'facebook': Facebook,
  'youtube': Youtube,
  'tiktok': Tiktok,
  'quote': Quote,
  'sparkles': Sparkles,
  'menu': Menu,
  'x': X,
  'log-out': LogOut,
  'lock': Lock,
  'save': Save,
  'trash-2': Trash2,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'sun': Sun,
  'moon': Moon,
  'user': User,
  'briefcase': Briefcase,
  'star': Star,
  'heart': Heart,
  'award': Award,
  'zap': Zap,
  'layers': Layers,
  'pen-tool': PenTool,
  'globe': Globe,
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'megaphone': Megaphone,
  'film': Film,
  'video': Video,
  'smartphone': Smartphone,
  'shopping-bag': ShoppingBag,
  'trending-up': TrendingUp,
  'compass': Compass,
  'target': Target,
  'gem': Gem,
  'crown': Crown,
  'brush': Brush,
  'shield-check': ShieldCheck,
  'pencil': Pencil,
  'wand-2': Wand2,
  'maximize': Maximize,
  'square': Square,
  'rectangle-horizontal': RectangleHorizontal,
  'rectangle-vertical': RectangleVertical,
  'file': FileIcon,
  'download': Download,
  'refresh-cw': RefreshCw,
  'inbox': Inbox,
  'calendar': Calendar,
  'copy': Copy,
}

export type IconName = keyof typeof ICONS

// Curated subset offered in the dashboard icon picker (content/service icons).
export const CONTENT_ICONS: string[] = [
  'palette', 'brush', 'pen-tool', 'pencil', 'printer', 'share-2', 'megaphone',
  'clapperboard', 'film', 'video', 'camera', 'box', 'layers', 'monitor',
  'smartphone', 'globe', 'shopping-bag', 'mail', 'sparkles', 'star', 'award',
  'gem', 'crown', 'rocket', 'zap', 'lightbulb', 'target', 'trending-up',
  'heart', 'shield-check', 'briefcase', 'users', 'compass', 'wand-2',
]
