-- ============================================================================
-- Nova Graphik — Promotions (page « Promotions » + section dashboard)
-- ----------------------------------------------------------------------------
-- A new public-facing "Promotions" page: one featured publication shown large,
-- the rest cycling in an auto-scrolling carousel. Each promotion carries a
-- publication type (`category`) and a predefined entrance animation key
-- (`animation`) chosen in the dashboard. Same RLS model as every other content
-- table: anon reads visible = 1, authenticated reads all + writes.
-- ============================================================================

create table if not exists public.promotions (
  id         bigint generated by default as identity primary key,
  title      text not null default '',
  slug       text not null default '',
  category   text not null default '',          -- type de publication (Flyer, Affiche, Story…)
  body       text not null default '',          -- description courte
  image      text not null default '',          -- visuel de la publication
  link_url   text not null default '',          -- lien optionnel (CTA)
  animation  text not null default 'fade',      -- clé d'animation prédéfinie
  featured   smallint not null default 0,       -- 1 = promo mise en avant (grand format)
  qr_target  text not null default '',          -- URL/texte encodé dans le QR code
  position   integer  not null default 0,
  visible    smallint not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists promotions_slug_idx on public.promotions (slug);

-- Row Level Security — identical pattern to the other content tables.
alter table public.promotions enable row level security;

drop policy if exists promotions_read on public.promotions;
create policy promotions_read on public.promotions for select
  using (visible = 1 or auth.role() = 'authenticated');

drop policy if exists promotions_write on public.promotions;
create policy promotions_write on public.promotions for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
