-- ============================================================================
-- Nova Graphik — Codes promo, page de détail & commandes
-- ----------------------------------------------------------------------------
-- Étend les promotions avec un contenu de page détail + un commerçant concerné +
-- une liste de codes promo (JSONB). Ajoute la table `orders` : la preuve durable
-- qu'un client a commandé avec un code promo Nova. L'e-mail (Edge Function
-- notify-order) n'est qu'une notification ; la commande est toujours enregistrée.
-- ============================================================================

-- ── Promotions : contenu détail + commerçant + codes promo ──────────────────
alter table public.promotions add column if not exists subtitle       text not null default '';
alter table public.promotions add column if not exists details        text not null default '';
alter table public.promotions add column if not exists conditions     text not null default '';
alter table public.promotions add column if not exists merchant_name  text not null default '';
alter table public.promotions add column if not exists merchant_email text not null default '';
alter table public.promotions add column if not exists valid_until    text not null default '';
-- codes = [{ code, label, discount, description }]
alter table public.promotions add column if not exists codes          jsonb not null default '[]'::jsonb;

-- ── Commandes (preuve de conversion via un code promo Nova) ──────────────────
create table if not exists public.orders (
  id              bigint generated by default as identity primary key,
  promotion_id    bigint,
  promotion_title text not null default '',
  promo_code      text not null default '',
  offer_label     text not null default '',
  customer_name   text not null default '',
  customer_email  text not null default '',
  customer_phone  text not null default '',
  message         text not null default '',
  status          text not null default 'nouveau',  -- nouveau | traité | annulé
  created_at      timestamptz not null default now()
);

create index if not exists orders_created_idx on public.orders (created_at desc);

-- RLS : tout le monde peut DÉPOSER une commande (formulaire public), seuls les
-- utilisateurs authentifiés (admin) peuvent les lire / modifier / supprimer.
alter table public.orders enable row level security;

drop policy if exists orders_insert on public.orders;
create policy orders_insert on public.orders for insert with check (true);

drop policy if exists orders_read on public.orders;
create policy orders_read on public.orders for select
  using (auth.role() = 'authenticated');

drop policy if exists orders_update on public.orders;
create policy orders_update on public.orders for update
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

drop policy if exists orders_delete on public.orders;
create policy orders_delete on public.orders for delete
  using (auth.role() = 'authenticated');
