-- ============================================================================
-- Nova Graphik — Supabase schema (Postgres + RLS + Storage)
-- ============================================================================
-- Run this once in the Supabase SQL editor (or via the CLI) on the project
-- whose URL/anon key the frontend already uses for auth.
--
-- Authorization model (per the brief): a single shared admin login. Therefore:
--   • anon (public visitors) can READ only rows marked visible = 1
--   • any authenticated user can READ everything and WRITE (insert/update/delete)
--   • settings are fully public to read (site config), authenticated to write
-- This mirrors exactly what the old Express + requireAdmin backend enforced.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tables
-- ----------------------------------------------------------------------------
create table if not exists public.sections (
  id         bigint generated by default as identity primary key,
  page       text   not null,
  type       text   not null,
  template   text   not null default 'text',
  title      text   not null default '',
  body       text   not null default '',
  icon       text   not null default '',
  image      text   not null default '',
  data       jsonb  not null default '{}'::jsonb,
  visible    smallint not null default 1,
  position   integer  not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id         bigint generated by default as identity primary key,
  name       text not null default '',
  role       text not null default '',
  bio        text not null default '',
  photo      text not null default '',
  slug       text not null default '',
  parent_id  bigint references public.team_members(id) on delete set null,
  position   integer  not null default 0,
  visible    smallint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
  id           bigint generated by default as identity primary key,
  title        text  not null default '',
  slug         text  not null default '',
  category     text  not null default '',
  description  text  not null default '',
  cover_image  text  not null default '',
  images       jsonb not null default '[]'::jsonb,
  external_url text  not null default '',
  position     integer  not null default 0,
  visible      smallint not null default 1,
  created_at   timestamptz not null default now()
);

create table if not exists public.settings (
  key   text primary key,
  value text not null default ''
);

create table if not exists public.nav_items (
  id       bigint generated by default as identity primary key,
  label    text not null,
  path     text not null,
  position integer  not null default 0,
  visible  smallint not null default 1
);

create table if not exists public.services (
  id          bigint generated by default as identity primary key,
  icon        text not null default 'sparkles',
  title       text not null,
  description text not null default '',
  position    integer  not null default 0,
  visible     smallint not null default 1
);

create table if not exists public.articles (
  id          bigint generated by default as identity primary key,
  title       text not null,
  slug        text not null default '',
  category    text not null default '',
  excerpt     text not null default '',
  body        text not null default '',
  cover_image text not null default '',
  date        text not null default '',
  position    integer  not null default 0,
  visible     smallint not null default 1,
  created_at  timestamptz not null default now()
);

create table if not exists public.partners (
  id       bigint generated by default as identity primary key,
  name     text not null,
  logo_url text not null default '',
  position integer  not null default 0,
  visible  smallint not null default 1
);

create table if not exists public.testimonials (
  id          bigint generated by default as identity primary key,
  quote       text not null,
  author_name text not null default '',
  author_role text not null default '',
  position    integer  not null default 0,
  visible     smallint not null default 1
);

create table if not exists public.pricing_items (
  id          bigint generated by default as identity primary key,
  group_title text not null default '',
  group_icon  text not null default '',
  name        text not null,
  description text not null default '',
  price       text not null default '',
  position    integer  not null default 0,
  visible     smallint not null default 1
);

create table if not exists public.pricing_formulas (
  id       bigint generated by default as identity primary key,
  name     text not null,
  price    text not null default '',
  features jsonb not null default '[]'::jsonb,
  is_hot   smallint not null default 0,
  position integer  not null default 0,
  visible  smallint not null default 1
);

create index if not exists sections_page_idx       on public.sections (page, position);
create index if not exists team_members_parent_idx on public.team_members (parent_id);
create index if not exists portfolio_slug_idx       on public.portfolio_items (slug);
create index if not exists articles_slug_idx        on public.articles (slug);

-- ----------------------------------------------------------------------------
-- Row Level Security
-- ----------------------------------------------------------------------------
-- Helper note: auth.role() = 'authenticated' for any logged-in Supabase user.

-- Content tables with a `visible` flag: public reads visible rows, admins read all.
do $$
declare t text;
begin
  foreach t in array array[
    'sections','team_members','portfolio_items','nav_items','services',
    'articles','partners','testimonials','pricing_items','pricing_formulas'
  ]
  loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists %I on public.%I;', t||'_read', t);
    execute format($f$
      create policy %I on public.%I for select
      using (visible = 1 or auth.role() = 'authenticated');
    $f$, t||'_read', t);

    execute format('drop policy if exists %I on public.%I;', t||'_write', t);
    execute format($f$
      create policy %I on public.%I for all
      using (auth.role() = 'authenticated')
      with check (auth.role() = 'authenticated');
    $f$, t||'_write', t);
  end loop;
end $$;

-- settings: fully public to read (site config), authenticated to write.
alter table public.settings enable row level security;
drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select using (true);
drop policy if exists settings_write on public.settings;
create policy settings_write on public.settings for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- ----------------------------------------------------------------------------
-- Storage: a single public `media` bucket for images & videos
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read on storage.objects for select
  using (bucket_id = 'media');

drop policy if exists media_auth_write on storage.objects;
create policy media_auth_write on storage.objects for all
  using (bucket_id = 'media' and auth.role() = 'authenticated')
  with check (bucket_id = 'media' and auth.role() = 'authenticated');
